service: flask-service

provider:
  name: aws
  runtime: python3.12
  stage: dev
  region: us-east-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http:
          path: /search
          method: get
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
